all: daysCalculatorA daysCalculatorB daysCalculatorC daysCalculatorD daysCalculatorE

daysCalculatorA: daysCalculatorA.o
	gcc -ansi -Wall -o daysCalculatorA daysCalculatorA.o

daysCalculatorA.o: daysCalculatorA.c
	gcc -ansi -Wall -c daysCalculatorA.c

daysCalculatorB: daysCalculatorB.o
	gcc -ansi -Wall -o daysCalculatorB daysCalculatorB.o

daysCalculatorB.o: daysCalculatorB.c
	gcc -ansi -Wall -c daysCalculatorB.c

daysCalculatorC: daysCalculatorC.o
	gcc -ansi -Wall -o daysCalculatorC daysCalculatorC.o

daysCalculatorC.o: daysCalculatorC.c
	gcc -ansi -Wall -c daysCalculatorC.c

daysCalculatorD: daysCalculatorD.o
	gcc -ansi -Wall -o daysCalculatorD daysCalculatorD.o

daysCalculatorE.o: daysCalculatorE.c
	gcc -ansi -Wall -c daysCalculatorE.c

clean:
	rm daysCalculatorA daysCalculatorB daysCalculatorC daysCalculatorD daysCalculatorE
